<?php

declare(strict_types=1);

$page_title           = 'Canvas Components - Fields';
$page_current         = 'canvas-components';
$component_page_links = canvas_links('components');

layout('canvas/layouts/canvas-start', [
  'page_title'         => $page_title,
  'page_current'       => $page_current,
  'canvas_primary'     => 'components',
  'canvas_links'       => $component_page_links,
  'canvas_active_link' => '/canvas/components/fields',
]);
?>
<section class="p-0">
  <?php component('header-page', [
    'header_topic'           => 'Components',
    'header_title'           => 'Fields',
    'header_subtitle'        => 'Reference for labeled field states, helper text patterns, and validation guidance.',
    'header_container_class' => 'w-full',
  ]); ?>
</section>

<section class="space-y-8">
  <section class="space-y-3">
    <h2 class="text-xl font-bold text-brand-900">Usage Rules</h2>
    <ul class="list-disc space-y-1 pl-5 text-base text-brand-700">
      <li>Always pair input controls with clear labels.</li>
      <li>Keep helper text concise and action-oriented.</li>
      <li>Use positive and negative states only when feedback is explicit.</li>
      <li>Reserve disabled fields for unavailable or read-only contexts.</li>
    </ul>
  </section>

  <section class="space-y-8">
    <div>
      <h3 class="text-xl font-bold text-brand-900">Default Field</h3>
      <p class="mt-2 max-w-3xl text-brand-600">
        Use as the baseline pattern for normal data entry without validation feedback.
      </p>
      <div class="mt-4 rounded-md border border-dashed border-brand-300 bg-white p-5">
        <?php component('form/field', [
          'label'       => 'Display name',
          'helper_text' => 'Shown on invoices and activity logs.',
          'state'       => 'default',
          'input_props' => [
            'type'        => 'text',
            'placeholder' => 'e.g., Aina Zulkifli',
          ],
          'class'       => 'space-y-2',
        ]); ?>
      </div>
    </div>

    <div>
      <h3 class="text-xl font-bold text-brand-900">Disabled Field</h3>
      <p class="mt-2 max-w-3xl text-brand-600">
        Use when a value is intentionally unavailable for editing in the current flow.
      </p>
      <div class="mt-4 rounded-md border border-dashed border-brand-300 bg-white p-5">
        <?php component('form/field', [
          'label'       => 'Workspace ID',
          'helper_text' => 'Generated by the system. This value cannot be edited.',
          'state'       => 'disabled',
          'input_props' => [
            'type'  => 'text',
            'value' => 'bkp_29f8a2c1',
          ],
          'class'       => 'space-y-2',
        ]); ?>
      </div>
    </div>

    <div>
      <h3 class="text-xl font-bold text-brand-900">Positive Field</h3>
      <p class="mt-2 max-w-3xl text-brand-600">
        Use to confirm a valid value after a successful validation check.
      </p>
      <div class="mt-4 rounded-md border border-dashed border-brand-300 bg-white p-5">
        <?php component('form/field', [
          'label'       => 'Recovery email',
          'helper_text' => 'Verified. We will use this email for account recovery.',
          'state'       => 'positive',
          'input_props' => [
            'type'  => 'email',
            'value' => 'ops@aurorastudio.my',
          ],
          'class'       => 'space-y-2',
        ]); ?>
      </div>
    </div>

    <div>
      <h3 class="text-xl font-bold text-brand-900">Negative Field</h3>
      <p class="mt-2 max-w-3xl text-brand-600">
        Use to highlight invalid input and tell users exactly what needs to be corrected.
      </p>
      <div class="mt-4 rounded-md border border-dashed border-brand-300 bg-white p-5">
        <?php component('form/field', [
          'label'       => 'Billing email',
          'helper_text' => 'Enter a valid work email, for example finance@aurorastudio.my.',
          'state'       => 'negative',
          'input_props' => [
            'type'  => 'email',
            'value' => 'finance@aurorastudio',
          ],
          'class'       => 'space-y-2',
        ]); ?>
      </div>
    </div>
  </section>
</section>
<?php layout('canvas/layouts/canvas-end'); ?>
