<?php

declare(strict_types=1);

$page_title           = 'Canvas Components - Fields';
$page_current         = 'canvas-components';
$component_page_links = canvas_links('components');

layout('canvas/layouts/canvas-start', [
  'page_title'         => $page_title,
  'page_current'       => $page_current,
  'canvas_primary'     => 'components',
  'canvas_links'       => $component_page_links,
  'canvas_active_link' => '/canvas/components/fields',
]);
?>
<section class="p-0">
  <?php
  $canvas_header = [
    'header_title'           => 'Fields',
    'header_subtitle'        => 'Reference for labeled field states, helper text patterns, and validation guidance.',
    'header_container_class' => 'w-full',
  ];
  component('canvas/header', ['canvas_header' => $canvas_header]);
?>
</section>

<section class="canvas-showcase grid md:grid-cols-2">
  <div class="canvas-demo first:border-r border-b border-dashed border-brand-300">
    <div class="flex h-full flex-col p-6">
      <div class="flex items-center justify-between border-b border-brand-200 pb-4 font-medium text-brand-900">
        Fields Base
      </div>
      <div class="relative flex min-h-[220px] items-center justify-center overflow-hidden bg-background px-6 py-8">
        <div class="flex w-full max-w-lg justify-center">
          <?php component('form/field', [
            'label'       => 'Display name',
            'helper_text' => 'Shown on invoices and activity logs.',
            'state'       => 'default',
            'input_props' => [
              'type'        => 'text',
              'placeholder' => 'e.g., Aina Zulkifli',
            ],
            'class'       => 'w-full space-y-2',
          ]); ?>
        </div>
      </div>
    </div>
  </div>
  <div class="canvas-demo first:border-r border-b border-dashed border-brand-300">
    <div class="flex h-full flex-col p-6">
      <div class="flex items-center justify-between border-b border-brand-200 pb-4 font-medium text-brand-900">
        Fields A
      </div>
      <div class="relative flex min-h-[220px] items-center justify-center overflow-hidden bg-background px-6 py-8">
        <div class="flex w-full max-w-lg justify-center">
          <?php component('form/field', [
            'label'       => 'Workspace ID',
            'helper_text' => 'Generated by the system. This value cannot be edited.',
            'state'       => 'disabled',
            'input_props' => [
              'type'  => 'text',
              'value' => 'bkp_29f8a2c1',
            ],
            'class'       => 'w-full space-y-2',
          ]); ?>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="canvas-showcase grid md:grid-cols-2">
  <div class="canvas-demo first:border-r border-b border-dashed border-brand-300">
    <div class="flex h-full flex-col p-6">
      <div class="flex items-center justify-between border-b border-brand-200 pb-4 font-medium text-brand-900">
        Fields B
      </div>
      <div class="relative flex min-h-[220px] items-center justify-center overflow-hidden bg-background px-6 py-8">
        <div class="flex w-full max-w-lg justify-center">
          <?php component('form/field', [
            'label'       => 'Recovery email',
            'helper_text' => 'Verified. We will use this email for account recovery.',
            'state'       => 'positive',
            'input_props' => [
              'type'  => 'email',
              'value' => 'ops@aurorastudio.my',
            ],
            'class'       => 'w-full space-y-2',
          ]); ?>
        </div>
      </div>
    </div>
  </div>
  <div class="canvas-demo first:border-r border-b border-dashed border-brand-300">
    <div class="flex h-full flex-col p-6">
      <div class="flex items-center justify-between border-b border-brand-200 pb-4 font-medium text-brand-900">
        Fields C
      </div>
      <div class="relative flex min-h-[220px] items-center justify-center overflow-hidden bg-background px-6 py-8">
        <div class="flex w-full max-w-lg justify-center">
          <?php component('form/field', [
            'label'       => 'Billing email',
            'helper_text' => 'Enter a valid work email, for example finance@aurorastudio.my.',
            'state'       => 'negative',
            'input_props' => [
              'type'  => 'email',
              'value' => 'finance@aurorastudio',
            ],
            'class'       => 'w-full space-y-2',
          ]); ?>
        </div>
      </div>
    </div>
  </div>
</section>
<?php layout('canvas/layouts/canvas-end'); ?>
